# Generated by Django 2.1.5 on 2019-01-22 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=2000, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=2000, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane', models.CharField(max_length=140, verbose_name='Name of Plane')),
                ('takeoff', models.CharField(max_length=140, verbose_name='Takeoff Speed')),
                ('glideslope', models.CharField(max_length=140, verbose_name='Glideslope Speed')),
                ('landing', models.CharField(max_length=140, verbose_name='Landing Speed')),
                ('dive', models.CharField(max_length=140, verbose_name='Dive Speed Limit')),
                ('supercharger', models.CharField(max_length=140, verbose_name='Supercharger')),
                ('fuel_load', models.CharField(max_length=140, verbose_name='Fuel Load')),
                ('endurance', models.CharField(max_length=140, verbose_name='Flight Endurance')),
                ('turn_sea', models.CharField(max_length=140, verbose_name='Maximum performance turn at sea level')),
                ('turn_3k', models.CharField(max_length=140, verbose_name='Maximum performance turn at 3000 m')),
                ('climb_sea', models.CharField(max_length=140, verbose_name='Climb rate at sea level')),
                ('climb_3k', models.CharField(max_length=140, verbose_name='Climb rate at 3000 m')),
                ('climb_6k', models.CharField(max_length=140, verbose_name='Climb rate at 6000 m')),
                ('stall_flight', models.CharField(max_length=140, verbose_name='Indicated stall speed in flight configuration')),
                ('stall_landing', models.CharField(max_length=140, verbose_name='Indicated stall speed in takeoff/landing configuration')),
            ],
        ),
        migrations.AddField(
            model_name='features',
            name='op_plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='il2.Plane', verbose_name='Plane Name'),
        ),
        migrations.AddField(
            model_name='engine',
            name='eng_plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='il2.Plane', verbose_name='Plane Name'),
        ),
    ]
