# Generated by Django 2.1.4 on 2019-02-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('il2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engine',
            new_name='Limits',
        ),
        migrations.AddField(
            model_name='plane',
            name='ceiling',
            field=models.CharField(default='', max_length=140, verbose_name='Service ceiling'),
        ),
        migrations.AddField(
            model_name='plane',
            name='debut',
            field=models.CharField(default='', max_length=140, verbose_name='Combat Debut'),
        ),
        migrations.AddField(
            model_name='plane',
            name='empty_weight',
            field=models.CharField(default='', max_length=140, verbose_name='Empty weight'),
        ),
        migrations.AddField(
            model_name='plane',
            name='max_weight',
            field=models.CharField(default='', max_length=140, verbose_name='Maximum takeoff weight'),
        ),
        migrations.AddField(
            model_name='plane',
            name='min_weight',
            field=models.CharField(default='', max_length=140, verbose_name='Minimum weight (no ammo, 10% fuel)'),
        ),
        migrations.AddField(
            model_name='plane',
            name='stall_flight_aoa',
            field=models.CharField(default='', max_length=140, verbose_name='Stall angle of attack in flight configuration'),
        ),
        migrations.AddField(
            model_name='plane',
            name='stall_landing_aoa',
            field=models.CharField(default='', max_length=140, verbose_name='Stall angle of attack in landing configuration'),
        ),
        migrations.AddField(
            model_name='plane',
            name='useful_load',
            field=models.CharField(default='', max_length=140, verbose_name='Useful load'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='climb_3k',
            field=models.CharField(default='', max_length=140, verbose_name='Climb rate at 3000 m'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='climb_6k',
            field=models.CharField(default='', max_length=140, verbose_name='Climb rate at 6000 m'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='climb_sea',
            field=models.CharField(default='', max_length=140, verbose_name='Climb rate at sea level'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='dive',
            field=models.CharField(default='', max_length=140, verbose_name='Dive Speed Limit'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='endurance',
            field=models.CharField(default='', max_length=140, verbose_name='Flight Endurance'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='fuel_load',
            field=models.CharField(default='', max_length=140, verbose_name='Fuel Load'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='glideslope',
            field=models.CharField(default='', max_length=140, verbose_name='Glideslope Speed'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='landing',
            field=models.CharField(default='', max_length=140, verbose_name='Landing Speed'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='plane',
            field=models.CharField(default='', max_length=140, verbose_name='Name of Plane'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='stall_flight',
            field=models.CharField(default='', max_length=140, verbose_name='Indicated stall speed in flight configuration'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='stall_landing',
            field=models.CharField(default='', max_length=140, verbose_name='Indicated stall speed in takeoff/landing configuration'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='supercharger',
            field=models.CharField(default='', max_length=140, verbose_name='Supercharger'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='takeoff',
            field=models.CharField(default='', max_length=140, verbose_name='Takeoff Speed'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='turn_3k',
            field=models.CharField(default='', max_length=140, verbose_name='Maximum performance turn at 3000 m'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='turn_sea',
            field=models.CharField(default='', max_length=140, verbose_name='Maximum performance turn at sea level'),
        ),
    ]
